---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by IssacSu.
--- DateTime: 2018/11/18 13:07
---
local Tank = require "app.Tank"
local AITank = class("AITank", Tank)

function AITank:ctor(node, name, map, camp)

    AITank.super.ctor(self, node, name, map, camp)

    self.OnCollide = function(obj)

        if iskindof(obj, "Bullet") then
            return
        end

        self:Redirect()

    end

    self.wait = 0
    self.lastRedirect = 0
    self:Redirect()
end

function AITank:Update()

    AITank.super.Update(self)

    if math.random(1, 100) < 2 then
        self:Fire()
    end

    if self.wait > 0 then
        local now = soket.gettime()

        if now - self.waitTimeStamp > self.wait then
            self.wait = 0
            self:Redirect()
        end
    end

end

local dirTable = { "left", "right", "up", "down" }

function AITank:Redirect()

    local now = socket.gettime()

    local dir

    --防止转向太快（小于0.5秒）
    if now - self.lastRedirect > 0.5 then
        dir = dirTable[math.random(1, #dirTable)]
    end

    self:SetDir(dir)

    --每次停止1~2秒
    if dir == nil then
        self.wait = math.random(1, 2)
        self.waitTimeStamp = socket.gettime()
    end

    self.lastRediect = now
end

return AITank
